### ISSUE TITLE
US16 - Pesquisar Departamento

### ISSUE THREAD

**Issue by rafaelrabetti** [fga-gpp-mds/2017.1-OndeE-UnB#40]
Eu como usuário, desejo consultar departamentos para que seja possível entender onde cada área de conhecimento está distribuído no campus.

Depende da US12 - Cadastrar Departamentos #36

- [ ] a pesquisa de departamentos deve possuir autocomplete ou sugestões;
- [ ] ao  encontrar um departamento deve-se destacá-lo no mapa;
- [ ] testes de aceitação.

**Comment by kairon-v** [comment]
Deve-se resolver o problema para buscar pelo nome e pelo acrônimo. No momento só está sendo possível procurar pelo acrônimo porque o título é um atributo de herança.

_apenas documentando um limitação_
