### ISSUE TITLE
TS08 - Melhorar Autocomplete

### ISSUE THREAD

**Issue by lucassoaresouza** [fga-gpp-mds/2017.1-OndeE-UnB#63]
Eu como desenvolvedor desejo que o autocomplete da busca do sistema mostre, somente, resultados que possuam a sub_string pesquisada para reduzir a quantidade dos resultados.

**Comment by kairon-v** [comment]
**Prédios** **Departamentos**

Deve-se resolver o problema para buscar pelo nome e pelo acrônimo. No momento só está sendo possível procurar pelo acrônimo porque o título é um atributo de herança.

_apenas documentando um limitação_
